### PR TITLE
Move test_utils

### PR DESCRIPTION
**Pull request by benrudolph**
@czue this moves the tests in `test_utils` to the `tests` folder with every other test. This allows us to run all the tests with `./manage test utils`. i tried for a while to get the setup working so that i could run them without our current infrastructure but it requires that you download a bunch of deps like django 1.3. decided this might be best considering the repo is already pretty closely tied to our infrastructure

### CODE REVIEW

**Comment by benrudolph** [comment]
buddy @orangejenny 
i think i may have to remove the travis hook from this repo

**Comment by millerdev** [comment]
> i think i may have to remove the travis hook from this repo

Does this mean tests for this repo will never be run automatically for new PRs? Can you explain why that seems reasonable? (it sounds bad to me)

**Comment by benrudolph** [comment]
majority of the tests aren't run on PR as far as i understand. if there's a way to hook it up to the main repo i think that'd be great

**Comment by benrudolph** [comment]
i take that back

**Comment by benrudolph** [comment]
ok so i think all the tests were run, but we can make travis much simpler than it currently is and hopefully much simpler to run the tests in this repo

**Comment by benrudolph** [comment]
do you happen to know how we usually handle this? >50% of our tests in the repo rely on the django test runner, so you need django to run the tests, which kind of defeats the purpose of this being a submodule independent of our django app right?

**Comment by millerdev** [comment]
> you need django to run the tests, which kind of defeats the purpose of this being a submodule independent of our django app right?

Not necessarily. I think it's probably reasonable (if not ideal) that dimagi-utils depends on django. Eliminating that dependency could have major benefits though. This is [the proverbial "utilities" module](http://yosefk.com/blog/redundancy-vs-dependencies-which-is-worse.html) aka "the trash can."

**Comment by benrudolph** [comment]
Hmm, OK, i agree with that, but the current state should change because i cannot run the tests that aren't run by the django runner. i think the solution here is to keep the django dep and move everything to django runner

**Comment by millerdev** [comment]
What do you think about using [django-nose](https://django-nose.readthedocs.org/en/latest/) to run these tests? I'm working over some analysis of switching our main test runner to use django-nose as well, but that's looking like a bit of a task because of other classes in our test runner hierarchy. Hopefully this repo should be simpler.

**Comment by millerdev** [comment]
btw, nose is an awesome test runner. I've used it in the past.

**Comment by benrudolph** [comment]
:heart: nose i'll check it out. thanks

**Pull request closed without merging**
