### PR TITLE
don't fail hard on email analytics tracking

### PR DESCRIPTION
**Pull request by czue**
http://manage.dimagi.com/default.asp?227529

@benrudolph @emord cc @biyeun

### CODE REVIEW

**Comment by benrudolph** [comment]
huh interesting, is this cause the swiss ssl cert is messed up?

**Comment by benrudolph** [comment]
good find though

**Comment by czue** [comment]
I think it might be the root CA on the server or something, but I'm not totally sure and didn't dig in. it fails on `requests.get('https://https://www.google-analytics.com/')` which seems like it shouldn't be impacted by the server's own cert

**Comment by emord** [comment]
I think that the same thing happens on india. (assuming the double https was a typo here and not what you ran on the server)

**Comment by czue** [comment]
correct it was a typo. that's odd - i would have expected india to send multiple emails too then which i don't think it is

**Pull request merged**
