### PR TITLE
garbage collect before printing final usage

### PR DESCRIPTION
**Pull request by proteusvacuum**
@emord
Forgot to push this a while ago

### CODE REVIEW

**Comment by emord** [comment]
Does that actually work? I thought most languages let you call things like this, but almost never actually garbage collect.

**Comment by emord** [comment]
:+1: on :white_check_mark:

**Comment by proteusvacuum** [comment]
It's more like "hey python, if you get a second, could you take out the trash? if not, no worries, but it's getting kinda gross in here". So, no, doesn't work always, but it's better than not asking.

**Comment by emord** [comment]
Yeah that's what I expected to happen. agreed seems better to at least ask

**Pull request merged**
