### PR TITLE
Django17

### PR DESCRIPTION
**Pull request by emord**
Test fails until we release new couchdbkit (passes locally) (just dependent on this version bump https://github.com/dimagi/couchdbkit/pull/8)

cc: @gcapalbo

### CODE REVIEW

**Comment by gcapalbo** [comment]
Looks good.  Looks like https://github.com/dimagi/couchdbkit/pull/8 was merged but the tests here still fail.  Is there something else that needs to happen for the tests to pass?

**Comment by emord** [comment]
Yeah. We need to deploy the update on pypi (same here https://github.com/dimagi/pillowtop/pull/120)

I'll do this on Monday and update the PRs.

**Comment by emord** [comment]
:white_check_mark: after jsonobject-couchdbkit upgrade

**Comment by gcapalbo** [comment]
@emord ready to merge from my side, but wasn't sure from your last comment - does another upgrade need to happen that we're waiting for?

**Comment by emord** [comment]
Sorry. Meant that tests passed after the upgrade happened. good to merge from me

**Pull request merged**
