### PR TITLE
Add util for handling two-way sync between couch and sql models

### PR DESCRIPTION
**Pull request by gcapalbo**
@TylerSheffels 

@czue Fyi, this is basically the same migration process you used for the xfoms session migration. Going to be using this to migrate some of the messaging models off couch.

### CODE REVIEW

**Comment by czue** [comment]
nice this looks great. a test could be nice - could probably easily port one from the xform sessions?

**Comment by czue** [comment]
(my comment isn't blocking merge but i'll wait to see if you agree)

**Comment by gcapalbo** [comment]
@czue I agree the tests would be good but if I put the tests in this repo then I'd have to create models here for testing in which case those dummy models would also end up in production.  So I'd have to put the tests on the actual models I'm migrating, right?  Let me know if I'm missing something.

**Comment by czue** [comment]
ah, good point. I think maybe you could define models in the tests file but would likely require a bit of bootstrapping code to setup the db in the test and not obviously worth it onw.

**Pull request merged**
