### PR TITLE
slightly more robust to_function

### PR DESCRIPTION
**Pull request by snopoke**
http://manage.dimagi.com/default.asp?171592

@TylerSheffels

### CODE REVIEW

**Comment by snopoke** [comment]
@TylerSheffels added some tests and also changed the implementation slightly. The case that was failing in this ticket was `test_to_function_package_level`

**Comment by czue** [comment]
:+1: after tests

**Comment by TylerSheffels** [comment]
Also :+1: after tests

**Comment by czue** [comment]
build fail still happening?
```
======================================================================
FAIL: test_to_function_package_level (dimagi.utils.tests.test_modules.ModulesTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dimagi/dimagi-utils/dimagi/utils/tests/test_modules.py", line 22, in test_to_function_package_level
    self.assertTrue(inspect.isfunction(fn))
AssertionError: False is not true
----------------------------------------------------------------------
```

**Pull request merged**
