### PR TITLE
Handle bulk transactions (ugly as sin)

### PR DESCRIPTION
**Pull request by benrudolph**
@dannyroberts @emord https://manage.dimagi.com/default.asp?255224

Today Derek tried to upload fixtures and when he did, it [error'd when saving](https://sentry.io/dimagi/commcarehq/issues/259794455/) due to a conflict error (he had tried to do multiple uploads. This had pretty awful consequence because we first delete all the fixtures and then save them. So if delete succeeds and save doesn't... well you're in a pickle.

This PR refactors to do deleting and saving in one request and uses `all_or_nothing`. It also groups the docs by db instead of class so it's more atomic. It's still not completely transactional if you use multiple dbs, but I don't think there's a way around it. If you guys are OK with it, I think I might move this entire class to `corehq/util/couch.py`. It's only used in fixture code and I've added a dependency on HQ... It's ugly for sure, so open to suggestions for how we can make this cleaner

### CODE REVIEW

**Comment by benrudolph** [comment]
wow bummer. i think this is still better and we could possibly use: Transaction Mode: All-or-nothing which will do the same thing

**Comment by dannyroberts** [comment]
yeah, all or nothing isn't exactly what we want; the "ideal" behavior, is for it to 409 conflict if there's _any_ conflict, but that's not what all or nothing does in couch: force-writes when there's a conflict, leaving conflicting versions—and couch will deterministically but _arbitrarily_ promote one of the two conflicting versions to head. The "none" part of "all or none" only happens if the plug is pulled on couch mid bulk save and it has to recover.

**Comment by dannyroberts** [comment]
The only transactions you can rely on are at the doc level—i.e. a single doc save happens entirely or not at all.

So if you want to make fixtures save transactionally, you'd have to do something like the following:

1. For each fixture type slug, have a doc that contains the _id of the fixture type that's "master" for that slug.
2. When you want to replace a whole fixture table, create a new fixture type doc and all its new fixture item docs
3. If the whole creation goes through smoothly, then promote that fixture type to master.
4. Create a background task to garbage collect the replaced fixture types/items

I realize this is a total pain. But that's pretty much the only way to do something like that.

**Comment by dannyroberts** [comment]
That said, just catching the error from bulk_save and continuing would probably get you most of the way there. IIRC, bulk_save will _save everything it can and return conflicts for everything else_.

couchdbkit has the lines

```python
        if errors:
            raise BulkSaveError(errors, results)
```

in its `save_docs` (== `bulk_save`) method, so if you `except BulkSaveError as e` then you should be able to check `e.errors` for any conflicts. And at the very least you can continue to finish the other replacements so you're not left with empty tables.

**Comment by benrudolph** [comment]
Thanks for the detailed response Danny. I didn't initially realize that from reading this in the docs:
> n short, there are none (by design). However, you can ask CouchDB to check that all the documents in your _bulk_docs request pass all your validation functions. If even one fails, none of the documents are written. You can select this mode by including "all_or_nothing":true in your request. With this mode, if all documents pass validation, then all documents will be updated, even if that introduces a conflict for some or all of the documents.

> and couch will deterministically but arbitrarily promote one of the two conflicting versions to head.
that part is ridiculous and i think is a show stopper. 

do you think it's worth still going this route if i drop `all_or_nothing` and handle the conflict errors? i can't tell if that is that much better than our current situation. it seems to the exact same thing could happen again

**Comment by dannyroberts** [comment]
Yeah so I don't know what the actual behavior is, but my guess is that there are multiple bulk-saves involved right now in a single excel upload. That means that if any of them fails, then after the upload failure, the job of rebuilding/replacing any of the tables that would have been subsequently saved is just left undone, so those lookup tables just stay empty. If my mental model here is right, then just catching the `BulkSaveError` and continuing with the rest of the work it was going to do is going to at the very least get most of these things right. The only weird thing that happens is that this processe's writes lose to the other conflicting writes when they exist—everything else will go through though, even in the same bulk-save I believe.

(There's the separate problem that no matter what right now, during an upload for some (possibly brief) period of time, these lookup tables will just be either totally empty or only partially there, which may cause weird restore behavior on a very active domain.)

Also, it's a pretty great coincidence that this PR is https://github.com/dimagi/dimagi-utils/pull/409 :)

**Pull request closed without merging**
