### PR TITLE
default to None to allow differenciating between False and not set

### PR DESCRIPTION
**Pull request by snopoke**
@calellowitz

### CODE REVIEW

**Comment by snopoke** [comment]
This should fix the build: https://github.com/dimagi/couchdbkit/pull/19/files

**Comment by calellowitz** [comment]
build still failing in a way that looks related but not exactly sure why

**Comment by snopoke** [comment]
take 2 https://github.com/dimagi/couchdbkit/pull/20

**Comment by snopoke** [comment]
:white_check_mark:

**Pull request merged**
